# logging configuration
logging.path=tmp/logs

# db configuration
spring.data.mongodb.uri=mongodb+srv://srikanthp:6RR8CXG9owQPLwD6@cluster0.2b4vvfk.mongodb.net/axcl-dev

# AWS S3 configuration
aws.s3.accessKeyId=AKIAYHJANSE77ZXBrrVORP
aws.s3.accessKeySecret=93erH4TQLr0rrtjAJayuYBT6jAtlIlFVjylsBAu9/o
aws.s3.regionName=ap-south-1
aws.s3.bucketName=dev-axcl-documents
aws.s3.preSignedUrlExpiryInMillis=600000

# jwt configuration
jwt.signing.key=axcl_secret_2275c9f80692773

# exception notification triggering keys
unhandled.issues.notifications.email=false
unhandled.issues.notifications.email.users=srikanth.p@innocito.com

# mongock configuration
mongock.enabled=false