# logging configuration
logging.path=/tmp/logs
# aws secret manager configuration
spring.cloud.aws.region.static=ap-south-1
spring.config.import=aws-secretsmanager:dev-axcl_drivers_service_java-secrets