# logging configuration
logging.path=tmp/logs

# db configuration
spring.datasource.url=jdbc:postgresql://ep-little-salad-aesgwssy-pooler.c-2.us-east-2.aws.neon.tech:5432/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=npg_3BMYzZJDCUl1
spring.datasource.driver-class-name=org.postgresql.Driver

# AWS S3 configuration
aws.s3.accessKeyId=AKIAYHJANSE77ZXBrrVORP
aws.s3.accessKeySecret=93erH4TQLr0rrtjAJayuYBT6jAtlIlFVjylsBAu9/o
aws.s3.regionName=ap-south-1
aws.s3.bucketName=dev-axcl-documents
aws.s3.preSignedUrlExpiryInMillis=600000

# AWS SQS configuration for webhook queue.
sentry.webhook.aws.sqs.accessKeyId=AKIAV7RETUBGT6VP6AUG
sentry.webhook.aws.sqs.accessKeySecret=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
sentry.webhook.aws.sqs.regionName=us-gov-east-1
sentry.webhook.aws.sqs.queueName=dev_sqs_axcl.fifo
sentry.webhook.aws.sqs.endpoint=https://sqs.us-gov-east-1.amazonaws.com/411319902285/dev_sqs_axcl.fifo

# jwt configuration
jwt.signing.key=axcl_secret_2275c9f80692773

# exception notification triggering keys
unhandled.issues.notifications.email=false
unhandled.issues.notifications.email.users=srikanth.p@innocito.com

# sentry webhook secret
sentry.webhook.client.secret=dev-axcl-sentry-webhook-client-secret-#24234234$
