spring.profiles.active=local
app.name=axcl_external_integration_java
app.version=@project.version@

# db configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# jackson mapper configuration
spring.jackson.mapper.accept-case-insensitive-enums=true
spring.jackson.mapper.allow-coercion-of-scalars=false

# file upload configuration
spring.servlet.multipart.max-file-size=8MB
spring.servlet.multipart.max-request-size=8MB

# image upload configurations
image.upload.allowed.file.extensions=jpg,jpeg,png
image.upload.allowed.content.types=image/jpeg,image/png